apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-vault-secrets
spec:
  provider: azure
  secretObjects:                                 
  - secretName: mysql-db-password
    type: Opaque
    data: 
    - objectName: secretalias                    
      key: db-password 
  parameters:
    usePodIdentity: "true"   
    useVMManagedIdentity: "false"         
    userAssignedIdentityID: "servicePrincipalClientID"       
    keyvaultName: "Usermgmtwebapp-mysqldb"
    cloudName: ""        
    objects:  |
      array:
        - |
          objectName: mysq-db-password                
          objectType: secret                  
          objectAlias: mysql-db-password
          objectVersion: ""                   
    resourceGroup: "aks-rg4"     
    subscriptionId: "82808767-144c-4c66-a320-b30791668b0a"          
    tenantId: "c81f465b-99f9-42d3-a169-8082d61c677a"                      