apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium # Using AKS provisioned storage class
  resources:
    requests:
      storage: 5Gi      

# AKS already provisioned Storage classes managed-premium and default as part of 
# default cluster setup      